git clone https://github.com/ShiftMediaProject/bzip2.git
git clone git@github.com:ShiftMediaProject/fontconfig.git
git clone git@github.com:ShiftMediaProject/freetype2.git
git clone git@github.com:ShiftMediaProject/fribidi.git
git clone git@github.com:ShiftMediaProject/game-music-emu.git
git clone git@github.com:ShiftMediaProject/gmp.git
git clone git@github.com:ShiftMediaProject/gnutls.git
git clone git@github.com:ShiftMediaProject/harfbuzz.git
git clone git@github.com:ShiftMediaProject/lame.git
git clone git@github.com:ShiftMediaProject/libass.git
git clone git@github.com:ShiftMediaProject/libbluray.git
git clone git@github.com:ShiftMediaProject/libcdio.git
git clone git@github.com:ShiftMediaProject/libcdio-paranoia.git
git clone git@github.com:ShiftMediaProject/libgcrypt.git
git clone git@github.com:ShiftMediaProject/libgpg-error.git
git clone git@github.com:ShiftMediaProject/libiconv.git
git clone git@github.com:ShiftMediaProject/libilbc.git
git clone git@github.com:ShiftMediaProject/liblzma.git
git clone git@github.com:ShiftMediaProject/libssh.git
git clone git@github.com:ShiftMediaProject/libvpx.git
git clone git@github.com:ShiftMediaProject/libxml2.git
git clone git@github.com:ShiftMediaProject/mfx_dispatch.git
git clone git@github.com:ShiftMediaProject/modplug.git
git clone git@github.com:ShiftMediaProject/nettle.git
git clone git@github.com:ShiftMediaProject/ogg.git
git clone git@github.com:ShiftMediaProject/opus.git
git clone git@github.com:ShiftMediaProject/sdl.git
git clone git@github.com:ShiftMediaProject/soxr.git
git clone git@github.com:ShiftMediaProject/speex.git
git clone git@github.com:ShiftMediaProject/theora.git
git clone git@github.com:ShiftMediaProject/vorbis.git
git clone git@github.com:ShiftMediaProject/x264.git
git clone git@github.com:ShiftMediaProject/x265.git
git clone git@github.com:ShiftMediaProject/xvid.git
git clone git@github.com:ShiftMediaProject/zlib.git
